import React from 'react'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      
    </>
  )
}

export default page
