import AssignmentWriting from '@/components/AssignmentWriting';
import Feature from '@/components/Feature';
import Form from '@/components/Form';
import Home from '@/components/Home';
import KeyTopic from '@/components/KeyTopic';
import ServiceAssignment from '@/components/ServiceAssignment';
import StudentAssignment from '@/components/StudentAssignment';
import React from 'react'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <Home/>
      <Form/>
      <StudentAssignment/>
      <ServiceAssignment/>
      <AssignmentWriting/>
      <Feature/>
      <KeyTopic/>
    </>
  )
}

export default page
