import AssignmentWriting from '@/components/AssignmentWriting';
import Assistance from '@/components/Assistance';
import ChooseUs from '@/components/ChooseUs';
import Cta from '@/components/Cta';
import ExpertFrame from '@/components/ExpertFrame';
import Faq from '@/components/Faq';
import Feature from '@/components/Feature';
import Form from '@/components/Form';
import Home from '@/components/Home';
import HomeReview from '@/components/HomeReview';
import KeyTopic from '@/components/KeyTopic';
import Process from '@/components/Process';
import ServiceAssignment from '@/components/ServiceAssignment';
import StudentAssignment from '@/components/StudentAssignment';
import Testimonial from '@/components/Testimonial';
import React from 'react'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <Home/>
      <Form/>
      <StudentAssignment/>
      <ServiceAssignment/>
      <AssignmentWriting/>
      <Feature/>
      <KeyTopic/>
      <Cta/>
      <Assistance/>
      <HomeReview/>
      <ChooseUs/>
      <Testimonial/>
      <ExpertFrame/>
      <Faq/>
      <Process/>
    </>
  )
}

export default page
